theme: jekyll-theme-minimal
title: PPS-22-MetalScala3
logo: ./img/MetalSlug3Doc.png
description: "Project for the course of PPS-22-23: Metal Scala 3 "
show_downloads: true
github:
  private: false
  license:
    name: MIT
  repository_url: "https://github.com/MarzoliLeo/PPS-22-MetalScala3"
layout:
  width: 1000
  height: 800
