theme: jekyll-theme-minima
title: PPS-22-MetalScala3
description: "Project for the course of PPS-22-23: Metal Scala 3 "
github:
  private: false
  license:
    name: MIT
  repository_url: "https://github.com/MarzoliLeo/PPS-22-MetalScala3"
