name: Scala3 Build and Test

on:
  push:
    branches:
      - master  # Adjust this branch name to match your project's default branch

jobs:
  #This configuration will set up GitHub Actions to build and test your Scala 3 project for CI.
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Reference the major version of a release
      - uses: actions/checkout@v4
      # Reference a specific version
      - uses: actions/checkout@v4.2.0

      #Build and Test
      - name: Build and Test
        run: sbt test

      #Generate documentation
      - name: Generate Documentation
        run: sbt doc
